services:
  - type: web
    name: pereval-api-final
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pereval-db
          property: connectionString
      - key: INIT_DB_ON_START
        value: "1"

databases:
  - name: pereval-db
    databaseName: pereval_db
    user: pereval_user
    plan: free
